### ISSUE TITLE
关于 GMovieClip

### ISSUE THREAD

**Issue by zero16832** [fairygui/FairyGUI-as3#11]
在做项目得时候需要 对 GMovieClip的动画 进行 帧频的控制或者说 控制 动画的播放速度，然后查相关资料发现并没有对应的API可以使用。

**Comment by fairygui** [comment]
interval

**Comment by zero16832** [comment]
查阅 手册 并没有发现 interval?

**Comment by zero16832** [comment]
刚发现 unity 版本的 是有 interval 但是 as3版本 并没有 interval

**Comment by zero16832** [comment]
刚发现 unity 版本的 是有 interval 但是 as3版本 并没有 interval
