### ISSUE TITLE
关于 GMovieClip

### ISSUE THREAD

**Issue by zero16832** [fairygui/FairyGUI-as3#12]
莫名其妙地关了 上一个帖子~~
AS3 GMovileClip 没有 interval 这个API 这是BUG 么？

**Comment by fairygui** [comment]
源码都在这里，就不能自己搜一下吗，MovieClip里有interval，GMovieClip.displayObject就是MovieClip。

**Comment by zero16832** [comment]
我是看了源码发现没有才提的. GMovieClip.displayObject 是GObject

**Comment by zero16832** [comment]
找到了不好意思
