### ISSUE TITLE
关于 interval

### ISSUE THREAD

**Issue by zero16832** [fairygui/FairyGUI-as3#13]
好不容易找到了interval 发现改变数值之后 并不生效？

(movieClip.displayObject as MovieClip).interval = 24;

我这么使用它 修改之后发现并不生效，是我的使用方法有问题么？实在查不到资料，只能在这里提问了.

**Comment by zero16832** [comment]
使用代码后动画播放的效果 还是跟编辑器的效果一样的，我想实现的是动态改变 那个动画的帧频

**Comment by xiaoguzhu** [comment]
inteval的单位不是帧，是时间。
